language: go
go:
  - 1.13.x
env:
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
install:
  - curl https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-307.0.0-linux-x86_64.tar.gz | tar xfz - -C $HOME
  - $HOME/google-cloud-sdk/bin/gcloud components install beta cloud-datastore-emulator
  # JRE is needed for the datastore emulator
  - sudo apt-get install openjdk-8-jre-headless
script:
  - source $HOME/google-cloud-sdk/path.bash.inc
  - go mod download
  - go install github.com/go-bindata/go-bindata/v3/go-bindata
  - go install github.com/golang/mock/mockgen
  - go test -v -timeout=30s ./...
  - gofmt -w $(go list -f '{{.Dir}}' ./...)
  - go generate ./...
  - |
      # Check that `gofmt` and `go generate` resulted in no diffs.
      status=$(git status --porcelain)
      if [[ -n ${status} ]]; then
        echo "Regenerated files differ from checked-in versions: ${status}"
        git status
        git diff
        exit 1
      fi
